#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter
def company_logo(s):
    char_count = Counter(s)
    sorted_chars = sorted(char_count.items(), key=lambda x: (-x[1], x[0]))
    for char, count in sorted_chars[:3]:
        print(char, count)
if __name__ == '__main__':
    s = input().strip()
    company_logo(s)

