#!/bin/python3

import math
import os
import random
import re
import sys
import time
from datetime import datetime, timedelta

# Complete the time_delta function below.
def time_delta(t1, t2):
    format_string = "%a %d %b %Y %H:%M:%S %z" 
    t1 = datetime.strptime(t1, format_string)
    t2 = datetime.strptime(t2, format_string) 
    dif = abs(t1 - t2)
    return str(int(dif.total_seconds()))
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        t1 = input()

        t2 = input()

        delta = time_delta(t1, t2)

        fptr.write(delta + '\n')

    fptr.close()
